---
name: branches_pagination_without_count
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/50759
rollout_issue_url:
milestone: '13.9'
type: development
group: group::source code
default_enabled: false
