---
name: cached_loading_hints
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/61609
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/330802
milestone: '13.12'
type: development
group: group::source code
default_enabled: false
