---
name: cached_mr_title
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/61605
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/330907
milestone: '13.12'
type: development
group: group::source code
default_enabled: false
