---
name: ci_include_rules
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/67409
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/337507
milestone: '14.2'
type: development
group: group::pipeline authoring
default_enabled: false
