---
name: ci_idempotent_pipeline_process_worker
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/62410
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/332963
milestone: '14.0'
type: development
group: group::pipeline authoring
default_enabled: false
