---
name: dast_site_profile_disable_joins
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/66709
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/336945
milestone: '14.2'
type: development
group: group::dynamic analysis
default_enabled: true
