---
name: integrated_error_tracking
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/65767
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/335846
milestone: '14.1'
type: development
group: group::monitor
default_enabled: false
