---
name: limited_diff_highlighting
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/53768
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/323566
milestone: '13.12'
type: development
group: group::source code
default_enabled: true
