---
name: load_balancing_for_update_all_mirrors_worker
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/64526
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/334162
milestone: '14.1'
type: development
group: group::source code
default_enabled: false
