---
name: merge_request_show_render_cached
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/65217
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/335938
milestone: '14.2'
type: development
group: group::code review
default_enabled: false
