---
name: release_evidence
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/26509
rollout_issue_url: 
milestone: '12.10'
type: development
group: group::release
default_enabled: true
