---
name: specialized_worker_for_project_share_update_auth_recalculation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/61964
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/334234
milestone: '14.1'
type: development
group: group::access
default_enabled: false
