---
name: track_epic_boards_activity
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/60357
rollout_issue_url:
milestone: '13.12'
type: development
group: group::product planning
default_enabled: true
