---
name: usage_data_i_testing_load_performance_widget_total
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/52688
rollout_issue_url:
milestone: '13.9'
type: development
group: group::testing
default_enabled: true
