---
name: usage_data_i_testing_group_code_coverage_visit_total
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/51382
rollout_issue_url:
milestone: '13.8'
type: development
group: group::testing
default_enabled: true
