---
data_category: optional
key_path: usage_activity_by_stage.monitor.clusters
description: Users creating clusters.
product_section: ops
product_stage:
product_group: group::monitor
product_category: metrics
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
  - ce
  - ee
tier:
  - free
  - premium
  - ultimate
