---
data_category: optional
key_path: usage_activity_by_stage.plan.label_lists
description: Count of users creating label lists on Boards
product_section: dev
product_stage: plan
product_group: group::project management
product_category: boards
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
