---
data_category: optional
key_path: usage_activity_by_stage.manage.bulk_imports.gitlab_v1
description: Count of imports using GitLab Migration
product_section: dev
product_stage: manage
product_group: group::import
product_category: importers
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
