---
data_category: optional
key_path: counts.instances_custom_issue_tracker_active
description: Count of active instance-level integrations for a Custom Issue Tracker
product_section: dev
product_stage: ecosystem
product_group: group::integrations
product_category: integrations
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
performance_indicator_type: []
