---
data_category: optional
key_path: usage_activity_by_stage.monitor.projects_with_tracing_enabled
description: Projects with tracing enabled
product_section: ops
product_stage:
product_group: group::monitor
product_category: tracing
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
  - ce
  - ee
tier:
  - free
  - premium
  - ultimate
