---
data_category: optional
key_path: counts.package_events_i_package_container_pull_package
description: A count of container images that have been downloaded
product_section: ops
product_stage: package
product_group: group::package
product_category: container registry
value_type: number
status: deprecated
time_frame: all
data_source: redis
distribution:
- ee
- ce
tier:
- free
- premium
- ultimate
