---
data_category: optional
key_path: analytics_unique_visits.users_viewing_analytics_group_devops_adoption
name: "<please fill metric name, suggested format is: {subject}_{verb}{ing|ed}_{object} eg: users_creating_epics or merge_requests_viewed_in_single_file_mode>"
description:
product_section:
product_stage:
product_group:
product_category:
value_type: number
status: data_available
milestone: "13.12"
introduced_by_url:
time_frame: all
data_source:
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
skip_validation: true
