---
data_category: optional
key_path: usage_activity_by_stage.verify.clusters_applications_runner
description: Count of users creating managed clusters with Runner enabled
product_section: ops
product_stage: configure
product_group: group::configure
product_category: kubernetes_management
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate