---
data_category: optional
key_path: usage_activity_by_stage.manage.user_auth_by_provider.two-factor-via-u2f-device
description: Number of unique user logins using two factor via a U2F device
product_section: dev
product_stage: manage
product_group: group::access
product_category: authentication_and_authorization
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
tier:
- free
- premium
- ultimate
