---
data_category: optional
key_path: counts_weekly.aggregated_metrics.code_review_category_monthly_active_users
name: "0"
description:
product_section:
product_stage:
product_group:
product_category:
value_type: number
status: data_available
milestone: "13.12"
introduced_by_url:
time_frame: 7d
data_source:
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
skip_validation: true
