---
data_category: operational
key_path: usage_activity_by_stage_monthly.plan.service_desk_issues
description: Count of service desk issues
product_section: dev
product_stage: plan
product_group: group::plan
product_category: 
value_type: number
status: data_available
time_frame: 28d
data_source: database
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
performance_indicator_type: []
