---
data_category: optional
key_path: usage_activity_by_stage_monthly.manage.project_imports.bitbucket_server
description: Count of projects imported from Bitbucket Server
product_section: dev
product_stage: manage
product_group: group::import
product_category: importers
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
