---
data_category: optional
key_path: reply_by_email_enabled
description: Whether incoming email is setup
product_section: dev
product_stage: plan
product_group: group::certify
product_category: collection
value_type: boolean
status: data_available
time_frame: none
data_source: system
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
performance_indicator_type: []
