---
data_category: optional
key_path: mattermost_enabled
description: Whether Mattermost is enabled
product_section: dev
product_stage: ecosystem
product_group: group::integrations
product_category: integrations
value_type: boolean
status: data_available
time_frame: none
data_source: system
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
performance_indicator_type: []
